@authToken = {{authenticate.response.body.access_token}}

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luiz Eduardo",
    "email": "luiz.emplooye@test.com",
    "password": "12345678",
    "role": "emplooye",
    "departmentsIds": ["44cad2cc-c519-4fef-9c68-54565efd758e"],
    "benefitsIds": ["3ab17384-fa3c-4390-8359-e29175719400", "5c87eb0a-c9d9-4001-88cf-48de2b336268"]
}
###

# @name authenticate
POST http://localhost:3000/sessions
Content-Type: application/json

{
    "email": "luiz0223212@test.com",
    "password": "12345678"
}
###

GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authToken}} 
###

GET http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json
Authorization: Bearer {{authToken}} 
###

DELETE http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json
Authorization: Bearer {{authToken}} 
###

PUT http://localhost:3000/users/049459bf-2c99-45f5-9f57-ffc212577bc1
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Luiz Eduardo atualizado",
    "email": "luiz03atualizado@test.com",
    "password": "123456789",
    "role": "emplooye"
}
###

POST http://localhost:3000/departments
Content-Type:  application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Teste delete",
    "managerId": "049459bf-2c99-45f5-9f57-ffc212577bc1"
}
###
GET http://localhost:3000/departments
###

PUT http://localhost:3000/departments/44cad2cc-c519-4fef-9c68-54565efd758e
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Telemarketing",
    "userId": "5d1ccd73-85d3-457c-8a31-6cd3e2bfdd15"
    
}
###

DELETE http://localhost:3000/departments/44cad2cc-c519-4fef-9c68-54565efd758e
Content-Type: application/json
Authorization: Bearer {{authToken}} 
###

POST http://localhost:3000/benefits
Content-Type:  application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Vale transporte",
    "description": "Cartão para uso nos onibus para o trabalho",
    "value": 324.50
}
###
GET http://localhost:3000/benefits?description=plano
Authorization: Bearer {{authToken}} 
###

PUT http://localhost:3000/benefits/bcc12ebf-a65f-44bd-ae14-cceabb680e2c
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Plano de saúde master",
    "description": "descrição atualizada"
    
}
###

DELETE http://localhost:3000/benefits/bcc12ebf-a65f-44bd-ae14-cceabb680e2c
Content-Type: application/json
Authorization: Bearer {{authToken}} 
###

POST http://localhost:3000/payroll
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
    "name": "Relatório de pagamento",
    "firstPeriod": "2024-08-17",
    "lastPeriod": "2024-08-18",
    "departmentId": "44cad2cc-c519-4fef-9c68-54565efd758e",
    "month": 7,
    "year": 2024,
    "employeeId": "86b8ed20-6ce8-46a2-a5d2-3b0072012535",
    "hoursWorked": 168,
    "hourValue": 20
}
###