POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luiz Eduardo",
    "email": "luiz03@test.com",
    "password": "12345678",
    "role": "manager"
}
###

GET http://localhost:3000/users?email=luiz03@test.com
Content-Type: application/json
###

GET http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json
###

DELETE http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json