POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Luiz Eduardo",
    "email": "luiz022321@test.com",
    "password": "12345678",
    "role": "manager",
    "departmentsIds": ["44cad2cc-c519-4fef-9c68-54565efd758e"],
    "benefitsIds": ["4103f246-e0b8-47a2-ab1c-ab47a1296eac"]
}
###

GET http://localhost:3000/users
Content-Type: application/json
###

GET http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json
###

DELETE http://localhost:3000/users/0aabaf5c-3074-4435-ad61-11c93e43f94e
Content-Type: application/json
###

PUT http://localhost:3000/users/049459bf-2c99-45f5-9f57-ffc212577bc1
Content-Type: application/json

{
    "name": "Luiz Eduardo atualizado",
    "email": "luiz03atualizado@test.com",
    "password": "123456789",
    "role": "emplooye"
}
###

POST http://localhost:3000/departments
Content-Type:  application/json

{
    "name": "Teste delete",
    "managerId": "049459bf-2c99-45f5-9f57-ffc212577bc1"
}
###
GET http://localhost:3000/departments?managerId=049459bf-2c99-45f5-9f57-ffc212577bc1
###

PUT http://localhost:3000/departments/44cad2cc-c519-4fef-9c68-54565efd758e
Content-Type: application/json

{
    "name": "Telemarketing",
    "userId": "5d1ccd73-85d3-457c-8a31-6cd3e2bfdd15"
    
}
###

DELETE http://localhost:3000/departments/44cad2cc-c519-4fef-9c68-54565efd758e
Content-Type: application/json
###

POST http://localhost:3000/benefits
Content-Type:  application/json

{
    "name": "Plano de saúde",
    "description": "Plano de saúde que atende no pais inteiro sem cooparticipação(sonho)"
}
###
GET http://localhost:3000/benefits?description=plano
###

PUT http://localhost:3000/benefits/bcc12ebf-a65f-44bd-ae14-cceabb680e2c
Content-Type: application/json

{
    "name": "Plano de saúde master",
    "description": "descrição atualizada"
    
}
###

DELETE http://localhost:3000/benefits/bcc12ebf-a65f-44bd-ae14-cceabb680e2c
Content-Type: application/json
