
services:
  db:
    image: mysql:8
    container_name: challenge-lti-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=RH_management_system
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - app-network

  app:
    container_name: challenge-lti-app
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app 
    networks:
      - app-network 

volumes:
  mysql-volume:
    driver: local

networks:
  app-network: